# Generated by Django 5.2 on 2025-04-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studyreminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnesscheckin',
            name='note',
        ),
        migrations.AddField(
            model_name='wellnesscheckin',
            name='mood',
            field=models.CharField(choices=[('sad', '😞 Sad'), ('neutral', '😐 Neutral'), ('happy', '😊 Happy')], default='neutral', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wellnesscheckin',
            name='wellness_level',
            field=models.IntegerField(),
        ),
    ]
