# Generated by Django 5.2 on 2025-04-11 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_wellnesscheckin_note_wellnesscheckin_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnesscheckin',
            name='wellness_level',
        ),
        migrations.AlterField(
            model_name='wellnesscheckin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
