# Generated by Django 5.2 on 2025-04-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_wellnesscheckin_wellness_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WellnessEntry',
        ),
        migrations.RenameField(
            model_name='studyreminder',
            old_name='reminder_text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='wellnesscheckin',
            name='wellness_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wellnesscheckin',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
